// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: tms.proto

package productschemamodule

import (
	"context"

	"github.com/iscosmos/neurium/apps/tms/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateProductCategoryReq                        = pb.CreateProductCategoryReq
	CreateProductCategoryResp                       = pb.CreateProductCategoryResp
	CreateProductEndpointReq                        = pb.CreateProductEndpointReq
	CreateProductEndpointResp                       = pb.CreateProductEndpointResp
	CreateProductReq                                = pb.CreateProductReq
	CreateProductResp                               = pb.CreateProductResp
	CreateProductSchemaModuleReq                    = pb.CreateProductSchemaModuleReq
	CreateProductSchemaModuleResp                   = pb.CreateProductSchemaModuleResp
	DeleteProductCategoryReq                        = pb.DeleteProductCategoryReq
	DeleteProductCategoryResp                       = pb.DeleteProductCategoryResp
	DeleteProductEndpointReq                        = pb.DeleteProductEndpointReq
	DeleteProductEndpointResp                       = pb.DeleteProductEndpointResp
	DeleteProductReq                                = pb.DeleteProductReq
	DeleteProductResp                               = pb.DeleteProductResp
	DeleteProductSchemaModuleReq                    = pb.DeleteProductSchemaModuleReq
	DeleteProductSchemaModuleResp                   = pb.DeleteProductSchemaModuleResp
	GetProductCategoryReq                           = pb.GetProductCategoryReq
	GetProductCategoryResp                          = pb.GetProductCategoryResp
	GetProductCategoryTreeReq                       = pb.GetProductCategoryTreeReq
	GetProductCategoryTreeResp                      = pb.GetProductCategoryTreeResp
	GetProductCategoryTreeResp_ProductCategory      = pb.GetProductCategoryTreeResp_ProductCategory
	GetProductEndpointReq                           = pb.GetProductEndpointReq
	GetProductEndpointResp                          = pb.GetProductEndpointResp
	GetProductReq                                   = pb.GetProductReq
	GetProductResp                                  = pb.GetProductResp
	GetProductSchemaModuleReq                       = pb.GetProductSchemaModuleReq
	GetProductSchemaModuleResp                      = pb.GetProductSchemaModuleResp
	GetProductSchemaVersionReq                      = pb.GetProductSchemaVersionReq
	GetProductSchemaVersionResp                     = pb.GetProductSchemaVersionResp
	GetProductSchemaVersionWithReq                  = pb.GetProductSchemaVersionWithReq
	GetProductSchemaVersionWithResp                 = pb.GetProductSchemaVersionWithResp
	ListProductEndpointReq                          = pb.ListProductEndpointReq
	ListProductEndpointResp                         = pb.ListProductEndpointResp
	ListProductEndpointResp_ProductEndpoint         = pb.ListProductEndpointResp_ProductEndpoint
	ListProductReq                                  = pb.ListProductReq
	ListProductResp                                 = pb.ListProductResp
	ListProductResp_Product                         = pb.ListProductResp_Product
	ListProductSchemaModuleReq                      = pb.ListProductSchemaModuleReq
	ListProductSchemaModuleResp                     = pb.ListProductSchemaModuleResp
	ListProductSchemaModuleResp_ProductSchemaModule = pb.ListProductSchemaModuleResp_ProductSchemaModule
	ListProductSchemaReq                            = pb.ListProductSchemaReq
	ListProductSchemaResp                           = pb.ListProductSchemaResp
	ListProductSchemaResp_ProductSchema             = pb.ListProductSchemaResp_ProductSchema
	UpdateProductCategoryReq                        = pb.UpdateProductCategoryReq
	UpdateProductCategoryResp                       = pb.UpdateProductCategoryResp
	UpdateProductEndpointReq                        = pb.UpdateProductEndpointReq
	UpdateProductEndpointResp                       = pb.UpdateProductEndpointResp
	UpdateProductReq                                = pb.UpdateProductReq
	UpdateProductResp                               = pb.UpdateProductResp
	UpdateProductSchemaModuleReq                    = pb.UpdateProductSchemaModuleReq
	UpdateProductSchemaModuleResp                   = pb.UpdateProductSchemaModuleResp
	UpdateProductStatusReq                          = pb.UpdateProductStatusReq
	UpdateProductStatusResp                         = pb.UpdateProductStatusResp

	ProductSchemaModule interface {
		// 创建物模型模块
		CreateProductSchemaModule(ctx context.Context, in *CreateProductSchemaModuleReq, opts ...grpc.CallOption) (*CreateProductSchemaModuleResp, error)
		// 更新物模型模块
		UpdateProductSchemaModule(ctx context.Context, in *UpdateProductSchemaModuleReq, opts ...grpc.CallOption) (*UpdateProductSchemaModuleResp, error)
		// 删除物模型模块
		DeleteProductSchemaModule(ctx context.Context, in *DeleteProductSchemaModuleReq, opts ...grpc.CallOption) (*DeleteProductSchemaModuleResp, error)
		// 查看物模型模块
		GetProductSchemaModule(ctx context.Context, in *GetProductSchemaModuleReq, opts ...grpc.CallOption) (*GetProductSchemaModuleResp, error)
		// 物模型模块列表
		ListProductSchemaModule(ctx context.Context, in *ListProductSchemaModuleReq, opts ...grpc.CallOption) (*ListProductSchemaModuleResp, error)
	}

	defaultProductSchemaModule struct {
		cli zrpc.Client
	}
)

func NewProductSchemaModule(cli zrpc.Client) ProductSchemaModule {
	return &defaultProductSchemaModule{
		cli: cli,
	}
}

// 创建物模型模块
func (m *defaultProductSchemaModule) CreateProductSchemaModule(ctx context.Context, in *CreateProductSchemaModuleReq, opts ...grpc.CallOption) (*CreateProductSchemaModuleResp, error) {
	client := pb.NewProductSchemaModuleClient(m.cli.Conn())
	return client.CreateProductSchemaModule(ctx, in, opts...)
}

// 更新物模型模块
func (m *defaultProductSchemaModule) UpdateProductSchemaModule(ctx context.Context, in *UpdateProductSchemaModuleReq, opts ...grpc.CallOption) (*UpdateProductSchemaModuleResp, error) {
	client := pb.NewProductSchemaModuleClient(m.cli.Conn())
	return client.UpdateProductSchemaModule(ctx, in, opts...)
}

// 删除物模型模块
func (m *defaultProductSchemaModule) DeleteProductSchemaModule(ctx context.Context, in *DeleteProductSchemaModuleReq, opts ...grpc.CallOption) (*DeleteProductSchemaModuleResp, error) {
	client := pb.NewProductSchemaModuleClient(m.cli.Conn())
	return client.DeleteProductSchemaModule(ctx, in, opts...)
}

// 查看物模型模块
func (m *defaultProductSchemaModule) GetProductSchemaModule(ctx context.Context, in *GetProductSchemaModuleReq, opts ...grpc.CallOption) (*GetProductSchemaModuleResp, error) {
	client := pb.NewProductSchemaModuleClient(m.cli.Conn())
	return client.GetProductSchemaModule(ctx, in, opts...)
}

// 物模型模块列表
func (m *defaultProductSchemaModule) ListProductSchemaModule(ctx context.Context, in *ListProductSchemaModuleReq, opts ...grpc.CallOption) (*ListProductSchemaModuleResp, error) {
	client := pb.NewProductSchemaModuleClient(m.cli.Conn())
	return client.ListProductSchemaModule(ctx, in, opts...)
}
